
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 30 19:54:49 KST 2014
//----------------------------------------------------

package default_package;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ELSE = 21;
  public static final int PLUS = 27;
  public static final int RPAREN = 5;
  public static final int INT = 14;
  public static final int WHILE = 18;
  public static final int SEMI = 12;
  public static final int REL = 28;
  public static final int RETURN = 16;
  public static final int SWITCH = 22;
  public static final int IF = 20;
  public static final int RCBRACKET = 7;
  public static final int LPAREN = 4;
  public static final int COLON = 13;
  public static final int ID = 30;
  public static final int DO = 17;
  public static final int LSBRACKET = 8;
  public static final int COMMA = 10;
  public static final int FLOAT = 15;
  public static final int EOF = 0;
  public static final int BREAK = 24;
  public static final int FLOATNUM = 32;
  public static final int MULDIV = 26;
  public static final int MINUS = 3;
  public static final int CASE = 23;
  public static final int error = 1;
  public static final int EQ = 29;
  public static final int ASSIGN = 11;
  public static final int INTNUM = 31;
  public static final int DEFAULT = 25;
  public static final int RSBRACKET = 9;
  public static final int FOR = 19;
  public static final int LCBRACKET = 6;
  public static final int UMINUS = 2;
}

